name: Release Ubuntu

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os.runs-on }}
    
    strategy:
      matrix:
        os: 
          - runs-on: ubuntu-latest
            arch: linux-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Check version
        run: |
          TAG=${{ github.ref_name }}
          PROPERTIES_PATH=gradle.properties
          APP_VERSION=$(awk -F'=' '/^app.version/ {print $2}' $PROPERTIES_PATH)
          if [ "$TAG" != "$APP_VERSION" ]; then
            echo "Tag $TAG does not match app version $APP_VERSION"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageDeb

      - name: Rename
        run: |
          VERSION=${{ github.ref_name }}
          echo $VERSION
          PREFIX=$(echo $VERSION | cut -d'-' -f 1)
          echo $PREFIX
          mv ./build/compose/binaries/main/deb/vlabeler_$PREFIX-1_arm64.deb ./vlabeler-$VERSION-arm64.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: vlabeler-${{ github.ref_name }}-arm64.deb
